### ISSUE TITLE
Could not find 'blazorContextMenu.SetMenuHandlerReference' ('blazorContextMenu' was undefined)

### ISSUE THREAD

**Issue by nedimm** [KristofferStrube/Blazor.SVGEditor#16]
Hi Kristoffer,
I followed the steps for integrating the SVG Editor, but during the runtime I get the error below. 
I tried also manually to register the service without success. Could you help?
Best regards,
Nedim.

Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Could not find 'blazorContextMenu.SetMenuHandlerReference' ('blazorContextMenu' was undefined).
      Error: Could not find 'blazorContextMenu.SetMenuHandlerReference' ('blazorContextMenu' was undefined).
          at https://localhost:5002/_framework/blazor.webassembly.js:1:328
          at Array.forEach (<anonymous>)
          at a.findFunction (https://localhost:5002/_framework/blazor.webassembly.js:1:296)
          at _ (https://localhost:5002/_framework/blazor.webassembly.js:1:2442)
          at https://localhost:5002/_framework/blazor.webassembly.js:1:3330
          at new Promise (<anonymous>)
          at Object.beginInvokeJSFromDotNet (https://localhost:5002/_framework/blazor.webassembly.js:1:3311)
          at Object.Gt [as invokeJSFromDotNet] (https://localhost:5002/_framework/blazor.webassembly.js:1:62569)
          at Object.Ii (https://localhost:5002/_framework/dotnet.7.0.10.vzm6zpl6t5.js:5:71974)
          at _mono_wasm_invoke_js_blazor (https://localhost:5002/_framework/dotnet.7.0.10.vzm6zpl6t5.js:14:103886)
Microsoft.JSInterop.JSException: Could not find 'blazorContextMenu.SetMenuHandlerReference' ('blazorContextMenu' was undefined).
Error: Could not find 'blazorContextMenu.SetMenuHandlerReference' ('blazorContextMenu' was undefined).

**Comment by KristofferStrube** [comment]
I will get back to you tomorrow once I'm back from vacation. 😊

**Comment by nedimm** [comment]
Thank you for the fast reply Krostoffer!
I solved the problem. In a new Blazor app it works perfectly. In an "older" existing project I had to checkout Blazor.ContextMenu and reference it as a project in your library and now it works. Thank you for the great software !!!
Best Regards,
Nedim.

**Comment by KristofferStrube** [comment]
Cool that it was solved. 😊 If there is any changes to the README that could have made this process easier for you then feel free to make some pointers. 🙌

**Comment by nedimm** [comment]
Sure, I have just started using it. 
I will try to extend it in my fork and implement support for adding elements on left mouse button click in a separate toolbar (the functionality that we get from context menu at the moment).

**Comment by KristofferStrube** [comment]
I have made an example of extension-by-wrapping for the component in this repository which customizes the behaviour of the editor to make a general graph editor. https://github.com/KristofferStrube/Blazor.GraphEditor 

I think an approach like that would be better than forking the repository since you will be able to get the benefits of any future improvements or features I create. A feature that I think will improve the performance a lot is virtualization which is described in issue #15 .

**Comment by nedimm** [comment]
ok, I did not quite understand what do you mean. I just need the SVGEditor in one of pages. I can not see how should I use GraphEditor or how should I wrap the SVGEditor in order to be able to get future updates.

**Comment by KristofferStrube** [comment]
You mentioned that you have forked the project, which means that you will have to manually re-merge my repository into your repository to keep getting new updates.
The alternative is to use the NuGet package that is available for the SVGEditor and then add custom elements to the SVGEditor's SupportedElements parameter to add any custom functionality.

**Comment by nedimm** [comment]
ok thank you, I will try to do that. the problem is that I could not integrate the SVGEditor as nuget in my project because the service blazorContextMenu from the BlazorContextMenu project was not resolvable. I had to checkout BlazorContextMenu, recreate it and add it as a project reference to your checked-out project. Tried for hours all other approaches, it just did not work. With a fresh Blazor app I had not problems.

**Comment by nedimm** [comment]
unfortunatelly I am having no success working with the library. I have probably problems because of MudBlazor. I can for example create shapes but not resize because all anchor points appear black instead of hollow/white in a normal Blazor app and in your example. I can also not edit text once it has been added, but only in MudBlazor in your example app it works perfectly.
Any idea? Do I have to change some setting in order to make it editable?
Thanx.

**Comment by nedimm** [comment]
I have just created a fresh MudBlazor application with using only nuget package for SVGEditor. 
Unfortunatelly I can confirm that the library at this point does not work with MudBlazor:
https://imgur.com/jRDx71G
ColorPicker gets open without selected objects, SVG objects can not be resized or modified.
I can send you source code if you like. If you provide me instructions where to look and what to fix I will be glad to do that right now. 
Your project is very important at the moment for all of us and I would be glad if I can help in any way.

**Comment by KristofferStrube** [comment]
I would to love to help you debug if you will share the source code. It looks as though you are missing to add some CSS.

**Comment by nedimm** [comment]
that would be more than great :D
here is the code:
https://github.com/nedimm/SvgEditorMudBlazor
thanks for taking the time!!

**Comment by KristofferStrube** [comment]
I will check it out later today when I get off work.

**Comment by KristofferStrube** [comment]
Hey @nedimm, I found the problem.

You need to add the CSS file for the compiled Scoped CSS of your project, which also includes the scoped styles of my library. To fix that, you need to add the following StyleSheet link in your `index.html` file:
```
<link href="SVGEditorMudBlazor.styles.css" rel="stylesheet" />
```

And I also found that the manual inclusion of the ColorPicker JS file is no longer needed so you can remove this:
```
<script src="_content/BlazorColorPicker/colorpicker.js"></script>
```

I have updated the README accordingly with these details.

**Comment by nedimm** [comment]
thank you very much Kristoffer!!
That works great. If I can help you in the future in any way please conntact me. My email is as my family name (at) gmail.com
Thanks once again and good night!

**Comment by KristofferStrube** [comment]
Nice. I would love to follow your progress in using the library. You can contact me on x.com (Twitter), Mastodon, or at `i (at) kristoffer-strube.dk` if you have any questions.
