### ISSUE TITLE
SVGEditor code in a server-side app : System.InvalidOperationException: The current thread is not associated with the Dispatcher

### ISSUE THREAD

**Issue by pcarret** [KristofferStrube/Blazor.SVGEditor#2]
When using the SVGEditor code in a server-side app and editing the svg as text in **textarea** 

"System.InvalidOperationException: The current thread is not associated with the Dispatcher"
<SVG  @ref=SVG1 Input=@Input1 InputUpdated="(string s) => { Input1 = s; **StateHasChanged()**; }" />

After reading [this ](https://blazor-university.com/components/multi-threaded-rendering/invokeasync/)
<SVG  @ref=SVG1 Input=@Input1 InputUpdated="(string s) => { Input1 = s; **InvokeAsync(StateHasChanged)**; }" />
**Solve** the issue

**Comment by KristofferStrube** [comment]
Nice.

I will try to add a full Blazor Server sample with this addtion. :)

**Comment by KristofferStrube** [comment]
Hey @pcarret.
Long time since we talked last. I just wanted to share that I have added a Blazor Server example to prepare to release this to NuGet. Hope you are doing well.
