### ISSUE TITLE
Self Closing Tags Not Supported

### ISSUE THREAD

**Issue by RobertDenton01** [KristofferStrube/Blazor.SVGEditor#26]
The following SVG lines should both render in the same way. However, the set of the self-closing tags only renders the first object. Presumably it's not correctly identifying the tag is closed.
Does not work correctly:
`<rect x="120" y="380" height="125" width="140" fill="green" stroke="blue" stroke-width="2"/>
<circle cx="450" cy="300" r="80" stroke="green" stroke-width="1" fill="url('#purple_blue_up_right')"/>`
Does work correctly:
`<rect x="120" y="380" height="125" width="140" fill="green" stroke="blue" stroke-width="2"></rect>
<circle cx="450" cy="300" r="80" stroke="green" stroke-width="1" fill="url('#purple_blue_up_right')"></circle>`

**Comment by KristofferStrube** [comment]
Thanks for opening the issue. This is related to how the XML is parsed. I have seen the problem before but didn't get around to make an issue for it. I will investigate a way to mitigate this problem, hopefully without replacing the XML parser library.

**Comment by RobertDenton01** [comment]
Hi Kristoffer, thanks for the reply. It's a very nice application, it just happened that the first example I tried was formatted with the self-closing tags! I was very impressed with it otherwise, good job!
