### ISSUE TITLE
cannot run this project in Linux

### ISSUE THREAD

**Issue by allrightsreserved** [KristofferStrube/Blazor.SVGEditor#31]
This project runs well in windows x64, but not in Linux arm64, maybe some reference doesn't support Linux arm64.

**Comment by KristofferStrube** [comment]
Are you getting some specific error or could you elaborate on what does not work?

**Comment by allrightsreserved** [comment]
> Are you getting some specific error or could you elaborate on what does not work?

sorry, my fault, it works in linux, only one error about the colorpicker.js
![error](https://github.com/KristofferStrube/Blazor.SVGEditor/assets/14358954/b85e13f7-7fce-40e9-9abb-f5ad5956a1a3)
