### ISSUE TITLE
Disable Panning feature

### ISSUE THREAD

**Issue by adrien426** [KristofferStrube/Blazor.SVGEditor#35]
Hello,

I don't understand the purpose of the Disable Panning feature because I don't see any difference whether it is disabled or not. Could you please clarify?

Thank you.

[Link](https://kristofferstrube.github.io/Blazor.SVGEditor/Minimal)

**Comment by KristofferStrube** [comment]
Hey, @adrien426, it disables the possibility of panning on the canvas. If it is enabled, you can pan by holding down the middle button and moving the mouse, or if zooming is enabled, by hovering the mouse over the place you want to pan towards.

https://github.com/KristofferStrube/Blazor.SVGEditor/assets/11569642/3c47c7f4-9a85-4178-aff8-47e966d88eda
