### ISSUE TITLE
Bugix : `Elements.IndexOf(element)` value should be checked to avoid crashes

### ISSUE THREAD

**Issue by pcarret** [KristofferStrube/Blazor.SVGEditor#4]
When removing elements and adding new one then removing, it can crash

in SVG.razor.cs

```
        protected override void OnInitialized()
        {

            ElementSubject
                .Buffer(TimeSpan.FromMilliseconds(33))
                .Where(updates => updates.Count > 0)
                .Subscribe(updates =>
                {
                    updates
                        .Distinct()
                        .ToList()
                        .ForEach(element =>
                        {
                            ElementsAsHtml[Elements.IndexOf(element)] = element.ToHtml();
                        });
                    UpdateInput();
                });
        }
```
Don't you think `Elements.IndexOf(element)` value should be checked to secure the code and avoid crashes ?
![image](https://user-images.githubusercontent.com/7167627/142031232-68dca81c-32b8-4a49-9944-19dd7ae73718.png)

**Comment by KristofferStrube** [comment]
I think the solution to this problem is to make `Elements` private and add accessors that ensure `ElementsAsHtml` is updated accordingly when Elements is changed.

I will look into this.

**Comment by KristofferStrube** [comment]
I have separated the responsibility of the generated Html to each `ISVGElement` so that SVG doesn't have to handle that. So some nice Separation of Concerns.
