### ISSUE TITLE
Any idea on how to export such an SVG to some image format (jpg, png...)?

### ISSUE THREAD

**Issue by ABIOLI-COM** [KristofferStrube/Blazor.SVGEditor#9]
It's just all in the title... I would like to save 'thumbnails' of what is created by users, so to give them previews... There should be an easy way, blazor or javascript, to generate an image from an svg... but I cannot find it... :-(
A

**Comment by KristofferStrube** [comment]
It's not related to this project itself, but on that note... Generally what other people have done in .NET is either to use one of the projects specifically for this like Aspose but most of these are not feature complete for things like custom fonts but should be fine for what my SVG Editor supports editing. What others that wish full support do is to have a headless instance of Chromium on a server and then generating a screenshot of a SVG from that.

**Comment by ABIOLI-COM** [comment]
Thanks again for your support!
A
